# Generated by Django 3.0.4 on 2020-04-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55)),
                ('telefono', models.CharField(max_length=16)),
                ('nit', models.CharField(default='c/f', max_length=20)),
                ('direccion', models.CharField(default='ciudad', max_length=30)),
                ('cumpleanios', models.DateField(blank=True)),
                ('estrellas', models.IntegerField(default=0)),
                ('eliminado', models.BooleanField(default=False)),
                ('correo', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
