# Generated by Django 2.2.5 on 2019-11-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=55)),
                ('telefono', models.CharField(max_length=16)),
<<<<<<< HEAD
                ('nit', models.CharField(default='', max_length=20)),
=======
                ('nit', models.CharField(default='c/f', max_length=20)),
>>>>>>> develop
                ('direccion', models.CharField(default='ciudad', max_length=30)),
                ('cumpleanios', models.DateField()),
                ('estrellas', models.IntegerField()),
                ('eliminado', models.BooleanField(default=False)),
                ('correo', models.CharField(max_length=25)),
            ],
        ),
    ]
