# Generated by Django 3.0.4 on 2020-04-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cumpleanios',
            field=models.DateField(blank=True, null=True),
        ),
    ]
