/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import campos.Cliente;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import requestget.GetClientes;
import requests.EstructuraPostPut;
import requests.Requests;

/**
 *
 * @author Windows 8.1
 */
public class FClientes extends javax.swing.JPanel {

    List<EstructuraPostPut> postCliente = new ArrayList<>();
    List<EstructuraPostPut> putCliente = new ArrayList<>();
    List<String> variablesClientePost = new ArrayList<>();
    List<String> variablesClientePut = new ArrayList<>();
    Requests requests = new Requests();
    GetClientes requestGet = new GetClientes();
    DefaultTableModel clientes = new DefaultTableModel();
    int filaSeleccionada = -1;
    List<Cliente> listaClientes = new ArrayList<>();
    Cliente objetoActual;
    
    public FClientes() {
        initComponents();
        inicializarVarClientePost();
        inicializarVarClientePut();
        inicializarEstructuraClientePost();
        inicializarEstructuraClientePut();
        requestGet.get("http://localhost:8000/api/clientes/");
        clientes.addColumn("Código");
        clientes.addColumn("Nombre");
        clientes.addColumn("Teléfono");
        clientes.addColumn("Nit");
        clientes.addColumn("Dirección");
        clientes.addColumn("Cumpleaños");
        clientes.addColumn("Relevancia");
        clientes.addColumn("Correo");
        tClientes.setModel(clientes);
        cargarInformacion();
    }

    private void seleccionarCliente()
    {
        filaSeleccionada = tClientes.getSelectedRow();
        objetoActual = listaClientes.get(filaSeleccionada);
        decidirCategoriaSeleccionada();
        tfModNombre.setText(String.valueOf(tClientes.getValueAt(tClientes.getSelectedRow(), 1)));
        tfModTelefono.setText(String.valueOf(tClientes.getValueAt(tClientes.getSelectedRow(), 2)));
        tfModNit.setText(String.valueOf(tClientes.getValueAt(tClientes.getSelectedRow(), 3)));
        tfModDireccion.setText(String.valueOf(tClientes.getValueAt(tClientes.getSelectedRow(), 4)));
        tfModCumpleanos.setText(String.valueOf(tClientes.getValueAt(tClientes.getSelectedRow(), 5)));
        tfModCorreo.setText(String.valueOf(tClientes.getValueAt(tClientes.getSelectedRow(), 7)));
    }
    
    private void decidirCategoriaSeleccionada()
    {
        for (int i = 1; i < cbModRelevancia.getItemCount(); i++)
        {
            if (String.valueOf(tClientes.getValueAt(tClientes.getSelectedRow(), 6))
                    .equals(String.valueOf(cbModRelevancia.getItemAt(i))))
                cbModRelevancia.setSelectedIndex(i);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeneral = new javax.swing.JPanel();
        lblRelevancia = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        sepColor = new javax.swing.JSeparator();
        tfCodigo = new javax.swing.JTextField();
        sepCodigo = new javax.swing.JSeparator();
        tfNombre = new javax.swing.JTextField();
        sepNombre = new javax.swing.JSeparator();
        tfTelefono = new javax.swing.JTextField();
        sepModelo = new javax.swing.JSeparator();
        tfCumpleanos = new javax.swing.JTextField();
        tfCorreo = new javax.swing.JTextField();
        sepMarca = new javax.swing.JSeparator();
        btnIngresar = new javax.swing.JButton();
        lblInsercion = new javax.swing.JLabel();
        cbRelevancia = new javax.swing.JComboBox<>();
        lblCumpleanos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tClientes = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        tfNit = new javax.swing.JTextField();
        sepNombre1 = new javax.swing.JSeparator();
        lblNit = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        sepColor1 = new javax.swing.JSeparator();
        cbModRelevancia = new javax.swing.JComboBox<>();
        lblModNombre = new javax.swing.JLabel();
        tfModCumpleanos = new javax.swing.JTextField();
        sepModelo1 = new javax.swing.JSeparator();
        tfModTelefono = new javax.swing.JTextField();
        tfModCorreo = new javax.swing.JTextField();
        sepNombre2 = new javax.swing.JSeparator();
        sepMarca1 = new javax.swing.JSeparator();
        lblModRelevancia = new javax.swing.JLabel();
        lblModCumpleanos = new javax.swing.JLabel();
        lblModTelefono = new javax.swing.JLabel();
        tfModNombre = new javax.swing.JTextField();
        lblModCorreo = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        sepColor2 = new javax.swing.JSeparator();
        tfModNit = new javax.swing.JTextField();
        sepNombre3 = new javax.swing.JSeparator();
        lblModNit = new javax.swing.JLabel();
        lblModDireccion = new javax.swing.JLabel();
        tfModDireccion = new javax.swing.JTextField();
        sepColor3 = new javax.swing.JSeparator();
        btnModificar1 = new javax.swing.JButton();
        lblCorreo1 = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();

        pnlGeneral.setBackground(new java.awt.Color(34, 51, 59));
        pnlGeneral.setMinimumSize(new java.awt.Dimension(1280, 680));
        pnlGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRelevancia.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblRelevancia.setForeground(new java.awt.Color(255, 255, 255));
        lblRelevancia.setText("Relevancia");
        pnlGeneral.add(lblRelevancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("Código *");
        pnlGeneral.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        lblNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre *");
        pnlGeneral.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("Teléfono");
        pnlGeneral.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, -1, -1));
        pnlGeneral.add(sepColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 200, -1));

        tfCodigo.setBackground(new java.awt.Color(34, 51, 59));
        tfCodigo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfCodigo.setForeground(new java.awt.Color(255, 255, 255));
        tfCodigo.setBorder(null);
        tfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCodigoKeyTyped(evt);
            }
        });
        pnlGeneral.add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 200, -1));
        pnlGeneral.add(sepCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 200, -1));

        tfNombre.setBackground(new java.awt.Color(34, 51, 59));
        tfNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(255, 255, 255));
        tfNombre.setBorder(null);
        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreKeyTyped(evt);
            }
        });
        pnlGeneral.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 200, -1));
        pnlGeneral.add(sepNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 200, 10));

        tfTelefono.setBackground(new java.awt.Color(34, 51, 59));
        tfTelefono.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfTelefono.setForeground(new java.awt.Color(255, 255, 255));
        tfTelefono.setBorder(null);
        tfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTelefonoKeyTyped(evt);
            }
        });
        pnlGeneral.add(tfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, 200, -1));
        pnlGeneral.add(sepModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 200, -1));

        tfCumpleanos.setBackground(new java.awt.Color(34, 51, 59));
        tfCumpleanos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfCumpleanos.setForeground(new java.awt.Color(255, 255, 255));
        tfCumpleanos.setBorder(null);
        tfCumpleanos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCumpleanosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCumpleanosKeyTyped(evt);
            }
        });
        pnlGeneral.add(tfCumpleanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 200, -1));

        tfCorreo.setBackground(new java.awt.Color(34, 51, 59));
        tfCorreo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfCorreo.setForeground(new java.awt.Color(255, 255, 255));
        tfCorreo.setBorder(null);
        tfCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCorreoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCorreoKeyTyped(evt);
            }
        });
        pnlGeneral.add(tfCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 200, -1));
        pnlGeneral.add(sepMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 200, -1));

        btnIngresar.setBackground(new java.awt.Color(226, 98, 75));
        btnIngresar.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setFocusPainted(false);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        pnlGeneral.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 200, 60));

        lblInsercion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblInsercion.setForeground(new java.awt.Color(255, 255, 255));
        lblInsercion.setText("Insertar cliente");
        pnlGeneral.add(lblInsercion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        cbRelevancia.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cbRelevancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Muy poca relevancia", "Poca relevancia", "Más o menos relevante", "Mucha relevancia", "Bastante relevancia" }));
        cbRelevancia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRelevanciaItemStateChanged(evt);
            }
        });
        cbRelevancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbRelevanciaMouseReleased(evt);
            }
        });
        cbRelevancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRelevanciaActionPerformed(evt);
            }
        });
        cbRelevancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbRelevanciaKeyReleased(evt);
            }
        });
        pnlGeneral.add(cbRelevancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 200, 30));

        lblCumpleanos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblCumpleanos.setForeground(new java.awt.Color(255, 255, 255));
        lblCumpleanos.setText("Cumpleaños");
        pnlGeneral.add(lblCumpleanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 110, -1));

        tClientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Dirección", "Usuario"
            }
        ));
        tClientes.setFocusable(false);
        tClientes.getTableHeader().setReorderingAllowed(false);
        tClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tClientesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tClientesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tClientes);

        pnlGeneral.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 900, 140));
        pnlGeneral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1280, 10));

        tfNit.setBackground(new java.awt.Color(34, 51, 59));
        tfNit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfNit.setForeground(new java.awt.Color(255, 255, 255));
        tfNit.setBorder(null);
        tfNit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNitKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNitKeyTyped(evt);
            }
        });
        pnlGeneral.add(tfNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 200, -1));
        pnlGeneral.add(sepNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 200, 10));

        lblNit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblNit.setForeground(new java.awt.Color(255, 255, 255));
        lblNit.setText("Nit");
        pnlGeneral.add(lblNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("Dirección");
        pnlGeneral.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 110, -1));

        tfDireccion.setBackground(new java.awt.Color(34, 51, 59));
        tfDireccion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfDireccion.setForeground(new java.awt.Color(255, 255, 255));
        tfDireccion.setBorder(null);
        tfDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDireccionKeyTyped(evt);
            }
        });
        pnlGeneral.add(tfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 200, -1));
        pnlGeneral.add(sepColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, 200, -1));

        cbModRelevancia.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cbModRelevancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Muy poca relevancia", "Poca relevancia", "Más o menos relevante", "Mucha relevancia", "Bastante relevancia" }));
        cbModRelevancia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbModRelevanciaItemStateChanged(evt);
            }
        });
        cbModRelevancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbModRelevanciaMouseReleased(evt);
            }
        });
        cbModRelevancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModRelevanciaActionPerformed(evt);
            }
        });
        cbModRelevancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbModRelevanciaKeyReleased(evt);
            }
        });
        pnlGeneral.add(cbModRelevancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 200, 30));

        lblModNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblModNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblModNombre.setText("Nombre *");
        pnlGeneral.add(lblModNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        tfModCumpleanos.setBackground(new java.awt.Color(34, 51, 59));
        tfModCumpleanos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfModCumpleanos.setForeground(new java.awt.Color(255, 255, 255));
        tfModCumpleanos.setBorder(null);
        tfModCumpleanos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfModCumpleanosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfModCumpleanosKeyTyped(evt);
            }
        });
        pnlGeneral.add(tfModCumpleanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, 200, -1));
        pnlGeneral.add(sepModelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 380, 200, -1));

        tfModTelefono.setBackground(new java.awt.Color(34, 51, 59));
        tfModTelefono.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfModTelefono.setForeground(new java.awt.Color(255, 255, 255));
        tfModTelefono.setBorder(null);
        tfModTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfModTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfModTelefonoKeyTyped(evt);
            }
        });
        pnlGeneral.add(tfModTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, 200, -1));

        tfModCorreo.setBackground(new java.awt.Color(34, 51, 59));
        tfModCorreo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfModCorreo.setForeground(new java.awt.Color(255, 255, 255));
        tfModCorreo.setBorder(null);
        tfModCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfModCorreoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfModCorreoKeyTyped(evt);
            }
        });
        pnlGeneral.add(tfModCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, 200, -1));
        pnlGeneral.add(sepNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 200, 10));
        pnlGeneral.add(sepMarca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, 200, -1));

        lblModRelevancia.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblModRelevancia.setForeground(new java.awt.Color(255, 255, 255));
        lblModRelevancia.setText("Relevancia");
        pnlGeneral.add(lblModRelevancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        lblModCumpleanos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblModCumpleanos.setForeground(new java.awt.Color(255, 255, 255));
        lblModCumpleanos.setText("Cumpleaños");
        pnlGeneral.add(lblModCumpleanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 110, -1));

        lblModTelefono.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblModTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblModTelefono.setText("Teléfono");
        pnlGeneral.add(lblModTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, -1, -1));

        tfModNombre.setBackground(new java.awt.Color(34, 51, 59));
        tfModNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfModNombre.setForeground(new java.awt.Color(255, 255, 255));
        tfModNombre.setBorder(null);
        tfModNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfModNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfModNombreKeyTyped(evt);
            }
        });
        pnlGeneral.add(tfModNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 200, -1));

        lblModCorreo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblModCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblModCorreo.setText("Correo");
        pnlGeneral.add(lblModCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, -1, -1));

        btnModificar.setBackground(new java.awt.Color(226, 98, 75));
        btnModificar.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setFocusPainted(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        pnlGeneral.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 200, 70));
        pnlGeneral.add(sepColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 200, -1));

        tfModNit.setBackground(new java.awt.Color(34, 51, 59));
        tfModNit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfModNit.setForeground(new java.awt.Color(255, 255, 255));
        tfModNit.setBorder(null);
        tfModNit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfModNitKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfModNitKeyTyped(evt);
            }
        });
        pnlGeneral.add(tfModNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 200, -1));
        pnlGeneral.add(sepNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 200, 10));

        lblModNit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblModNit.setForeground(new java.awt.Color(255, 255, 255));
        lblModNit.setText("Nit");
        pnlGeneral.add(lblModNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        lblModDireccion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblModDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblModDireccion.setText("Dirección");
        pnlGeneral.add(lblModDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 110, -1));

        tfModDireccion.setBackground(new java.awt.Color(34, 51, 59));
        tfModDireccion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfModDireccion.setForeground(new java.awt.Color(255, 255, 255));
        tfModDireccion.setBorder(null);
        tfModDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfModDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfModDireccionKeyTyped(evt);
            }
        });
        pnlGeneral.add(tfModDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 200, -1));
        pnlGeneral.add(sepColor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 200, -1));

        btnModificar1.setBackground(new java.awt.Color(226, 98, 75));
        btnModificar1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btnModificar1.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar1.setText("Eliminar");
        btnModificar1.setFocusPainted(false);
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });
        pnlGeneral.add(btnModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 550, 120, 50));

        lblCorreo1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo1.setText("Correo");
        pnlGeneral.add(lblCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, -1, -1));

        lblModificar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblModificar.setText("Modificar cliente");
        pnlGeneral.add(lblModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarVarClientePost()
    {
        variablesClientePost.add("codigo");
        variablesClientePost.add("nombre");
        variablesClientePost.add("telefono");
        variablesClientePost.add("nit");
        variablesClientePost.add("direccion");
        variablesClientePost.add("cumpleanios");
        variablesClientePost.add("estrellas");
        variablesClientePost.add("correo");
    }
    
    private void inicializarVarClientePut()
    {
        variablesClientePut.add("nombre");
        variablesClientePut.add("telefono");
        variablesClientePut.add("nit");
        variablesClientePut.add("direccion");
        variablesClientePut.add("cumpleanios");
        variablesClientePut.add("estrellas");
        variablesClientePut.add("correo");
    }
    
    private void cargarInformacion()
    {
        Object O[] = null;
        listaClientes = (List<Cliente>)requestGet.get("http://localhost:8000/api/clientes/");
        for (int i = 0; i < listaClientes.size(); i++)
        {
            clientes.addRow(O);
            int estrellas = listaClientes.get(i).getEstrellas();
            clientes.setValueAt(listaClientes.get(i).getCodigo(), i, 0);
            clientes.setValueAt(listaClientes.get(i).getNombre(), i, 1);
            clientes.setValueAt(listaClientes.get(i).getTelefono(), i, 2);
            clientes.setValueAt(listaClientes.get(i).getNit(), i, 3);
            clientes.setValueAt(listaClientes.get(i).getDireccion(), i, 4);
            clientes.setValueAt(listaClientes.get(i).getCumpleanos(), i, 5);
            if (estrellas == 1)
                clientes.setValueAt("Muy poca relevancia", i, 6);
            else if (estrellas == 2)
                clientes.setValueAt("Poca relevancia", i, 6);
            else if (estrellas == 3)
                clientes.setValueAt("Más o menos relevante", i, 6);
            else if (estrellas == 4)
                clientes.setValueAt("Mucha relevancia", i, 6);
            else if (estrellas == 5)
                clientes.setValueAt("Bastante relevancia", i, 6);
            clientes.setValueAt(listaClientes.get(i).getCorreo(), i, 7);
        }
    }
    
    private void inicializarEstructuraClientePost()
    {
        for (int i = 0; i < variablesClientePost.size(); i++)
        {
            EstructuraPostPut estructuraPost = new EstructuraPostPut();
            estructuraPost.setVariable(variablesClientePost.get(i));
            postCliente.add(estructuraPost);
        }
    }
    
    private void inicializarEstructuraClientePut()
    {
        for (int i = 0; i < variablesClientePut.size(); i++)
        {
            EstructuraPostPut estructuraPost = new EstructuraPostPut();
            estructuraPost.setVariable(variablesClientePut.get(i));
            putCliente.add(estructuraPost);
        }
    }
    
    private void tfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER))
            tfNombre.requestFocus();
        else if (evt.getKeyCode() == KeyEvent.VK_UP)
            tfCumpleanos.requestFocus();
    }//GEN-LAST:event_tfCodigoKeyPressed

    private void tfCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoKeyTyped
        char c = evt.getKeyChar();

        if ((c < 'A')||(c > 'Z'))
        {
            if ((c < '0') || (c > '9'))
            evt.consume();
        }

        if (tfCodigo.getText().length()>15)
            evt.consume();
    }//GEN-LAST:event_tfCodigoKeyTyped

    private void tfNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER))
            tfCorreo.requestFocus();
        else if (evt.getKeyCode() == KeyEvent.VK_UP)
            tfCodigo.requestFocus();
    }//GEN-LAST:event_tfNombreKeyPressed

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyTyped
        char c = evt.getKeyChar();

        if ((c < 'a' || c > 'z') && (c < 'A')|c > 'Z')
        {
            if ((c != ' ') && (c != 'á') && (c != 'é') && (c != 'í') && (c != 'ó') && (c != 'ú'))
            evt.consume();
        }

        if (tfNombre.getText().length()>40)
            evt.consume();
    }//GEN-LAST:event_tfNombreKeyTyped

    private void tfTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER))
            tfCumpleanos.requestFocus();
        else if (evt.getKeyCode() == KeyEvent.VK_UP)
            tfCorreo.requestFocus();
    }//GEN-LAST:event_tfTelefonoKeyPressed

    private void tfTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0') || (c > '9'))
            evt.consume();
        if (tfTelefono.getText().length()>60)
            evt.consume();
    }//GEN-LAST:event_tfTelefonoKeyTyped

    private void tfCumpleanosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCumpleanosKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER))
            tfCodigo.requestFocus();
        else if (evt.getKeyCode() == KeyEvent.VK_UP)
            tfTelefono.requestFocus();
    }//GEN-LAST:event_tfCumpleanosKeyPressed

    private void tfCumpleanosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCumpleanosKeyTyped
        char c = evt.getKeyChar();

        if ((c < '0') || (c > '9')) {
            if (c != '-') {
                evt.consume();
            }
        }

        if (tfCumpleanos.getText().length()>10)
            evt.consume();
    }//GEN-LAST:event_tfCumpleanosKeyTyped

    private void tfCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCorreoKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER))
            tfTelefono.requestFocus();
        else if (evt.getKeyCode() == KeyEvent.VK_UP)
            tfNombre.requestFocus();
    }//GEN-LAST:event_tfCorreoKeyPressed

    private void tfCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCorreoKeyTyped
        char c = evt.getKeyChar();

        if ((c < 'a' || c > 'z') && (c < 'A')|c > 'Z')
        {
            if ((c != '@') && (c != '.'))
            {
                if ((c < '0') || (c > '9'))
                evt.consume();
            }
        }

        if (tfCorreo.getText().length()>45)
            evt.consume();
    }//GEN-LAST:event_tfCorreoKeyTyped

    private void cbRelevanciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRelevanciaItemStateChanged

    }//GEN-LAST:event_cbRelevanciaItemStateChanged

    private void cbRelevanciaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbRelevanciaMouseReleased

    }//GEN-LAST:event_cbRelevanciaMouseReleased

    private void cbRelevanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRelevanciaActionPerformed

    }//GEN-LAST:event_cbRelevanciaActionPerformed

    private void cbRelevanciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbRelevanciaKeyReleased

    }//GEN-LAST:event_cbRelevanciaKeyReleased

    private void tClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tClientesMouseClicked

    }//GEN-LAST:event_tClientesMouseClicked

    private void tClientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tClientesMouseReleased
        if (evt.getButton() == 1)
            seleccionarCliente();
    }//GEN-LAST:event_tClientesMouseReleased

    
    private void tfNitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNitKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER))
            tfCorreo.requestFocus();
        else if (evt.getKeyCode() == KeyEvent.VK_UP)
            tfNombre.requestFocus();
    }//GEN-LAST:event_tfNitKeyPressed

    private void tfNitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNitKeyTyped
        char c = evt.getKeyChar();

        if ((c < '0') || (c > '9')) {
            if (c != '-') {
                evt.consume();
            }
        }

        if (tfCumpleanos.getText().length()>10)
            evt.consume();        
    }//GEN-LAST:event_tfNitKeyTyped

    private void tfDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDireccionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDireccionKeyPressed

    private void tfDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDireccionKeyTyped
        if (tfCumpleanos.getText().length()>55)
            evt.consume();  
    }//GEN-LAST:event_tfDireccionKeyTyped

    private void cbModRelevanciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbModRelevanciaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModRelevanciaItemStateChanged

    private void cbModRelevanciaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbModRelevanciaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModRelevanciaMouseReleased

    private void cbModRelevanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModRelevanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModRelevanciaActionPerformed

    private void cbModRelevanciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbModRelevanciaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModRelevanciaKeyReleased

    private void tfModCumpleanosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModCumpleanosKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER))
            tfModNombre.requestFocus();
        else if (evt.getKeyCode() == KeyEvent.VK_UP)
            tfModTelefono.requestFocus();
    }//GEN-LAST:event_tfModCumpleanosKeyPressed

    private void tfModCumpleanosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModCumpleanosKeyTyped
        char c = evt.getKeyChar();

        if ((c < '0') || (c > '9')) {
            if (c != '-') {
                evt.consume();
            }
        }

        if (tfModCumpleanos.getText().length()>10)
            evt.consume();
    }//GEN-LAST:event_tfModCumpleanosKeyTyped

    private void tfModTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModTelefonoKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER))
            tfModCumpleanos.requestFocus();
        else if (evt.getKeyCode() == KeyEvent.VK_UP)
            tfModCorreo.requestFocus();
    }//GEN-LAST:event_tfModTelefonoKeyPressed

    private void tfModTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModTelefonoKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0') || (c > '9'))
            evt.consume();
        if (tfModTelefono.getText().length()>20)
            evt.consume();
    }//GEN-LAST:event_tfModTelefonoKeyTyped

    private void tfModCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModCorreoKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER))
            tfModTelefono.requestFocus();
        else if (evt.getKeyCode() == KeyEvent.VK_UP)
            tfModDireccion.requestFocus();
    }//GEN-LAST:event_tfModCorreoKeyPressed

    private void tfModCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModCorreoKeyTyped
        char c = evt.getKeyChar();

        if ((c < 'a' || c > 'z') && (c < 'A')|c > 'Z')
        {
            if ((c != '@') && (c != '.'))
            {
                if ((c < '0') || (c > '9'))
                evt.consume();
            }
        }

        if (tfModCorreo.getText().length()>45)
            evt.consume();
    }//GEN-LAST:event_tfModCorreoKeyTyped

    private void tfModNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModNombreKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER))
            tfModNit.requestFocus();
        else if (evt.getKeyCode() == KeyEvent.VK_UP)
            tfModCumpleanos.requestFocus();
    }//GEN-LAST:event_tfModNombreKeyPressed

    private void tfModNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModNombreKeyTyped
        char c = evt.getKeyChar();

        if ((c < 'a' || c > 'z') && (c < 'A')|c > 'Z')
        {
            if ((c != ' ') && (c != 'á') && (c != 'é') && (c != 'í') && (c != 'ó') && (c != 'ú'))
            evt.consume();
        }

        if (tfModNombre.getText().length()>40)
            evt.consume();
    }//GEN-LAST:event_tfModNombreKeyTyped

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (cbModRelevancia.getSelectedIndex() > 0 && tfModNombre.getText().length() > 0
                 && tfModCorreo.getText().length() > 0 && tfModTelefono.getText().length() > 0 && tfModCumpleanos.getText().length() > 0
                 && tfModNit.getText().length() > 0 && tfModDireccion.getText().length() > 0)
        {
            putCliente.get(0).setValor(tfModNombre.getText());
            putCliente.get(1).setValor(tfModTelefono.getText());
            putCliente.get(2).setValor(tfModNit.getText());
            putCliente.get(3).setValor(tfModDireccion.getText());
            putCliente.get(4).setValor(tfModCumpleanos.getText());
            putCliente.get(5).setValor(cbModRelevancia.getSelectedIndex());
            putCliente.get(6).setValor(tfModCorreo.getText());
            requests.put("http://localhost:8000/api/clientes/" + objetoActual.getCodigo() + "/", putCliente);
            tfModNombre.setText("");
            tfModTelefono.setText("");
            tfModCumpleanos.setText("");
            cbModRelevancia.setSelectedIndex(0);
            tfModCorreo.setText("");
            tfModNit.setText("");
            tfModCumpleanos.setText("");
            tfModDireccion.setText("");
            while (clientes.getRowCount() > 0) {
                clientes.removeRow(0);
            }
            cargarInformacion();
            JOptionPane.showMessageDialog(null, "Cliente modificado satisfactoriamente");
        }
        else
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tfModNitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModNitKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER))
            tfModDireccion.requestFocus();
        else if (evt.getKeyCode() == KeyEvent.VK_UP)
            tfModNombre.requestFocus();
    }//GEN-LAST:event_tfModNitKeyPressed

    private void tfModNitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModNitKeyTyped
        char c = evt.getKeyChar();

        if ((c < '0') || (c > '9')) {
            if (c != '-') {
                evt.consume();
            }
        }

        if (tfModCumpleanos.getText().length()>10)
            evt.consume();        
    }//GEN-LAST:event_tfModNitKeyTyped

    private void tfModDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModDireccionKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER))
            tfModCorreo.requestFocus();
        else if (evt.getKeyCode() == KeyEvent.VK_UP)
            tfModNit.requestFocus();
    }//GEN-LAST:event_tfModDireccionKeyPressed

    private void tfModDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModDireccionKeyTyped
        if (tfModCumpleanos.getText().length()>55)
            evt.consume();  
    }//GEN-LAST:event_tfModDireccionKeyTyped

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        if (filaSeleccionada != -1)
        {
            int input = JOptionPane.showConfirmDialog(null, "¿Eliminar producto?","Eliminar",JOptionPane.OK_CANCEL_OPTION);
            if (input == 0)
            {
                requests.delete("http://localhost:8000/api/clientes/" + objetoActual.getCodigo() + "/");
                JOptionPane.showMessageDialog(null, "Cliente eliminado");
                while (clientes.getRowCount() > 0) 
                    clientes.removeRow(0);
                cargarInformacion();
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Por favor seleccione un cliente");
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (cbRelevancia.getSelectedIndex() > 0 && tfCodigo.getText().length() > 0 && tfNombre.getText().length() > 0
            && tfCorreo.getText().length() > 0 && tfTelefono.getText().length() > 0 && tfCumpleanos.getText().length() > 0
            && tfNit.getText().length() > 0 && tfDireccion.getText().length() > 0)
        {
            postCliente.get(0).setValor(tfCodigo.getText());
            postCliente.get(1).setValor(tfNombre.getText());
            postCliente.get(2).setValor(tfTelefono.getText());
            postCliente.get(3).setValor(tfNit.getText());
            postCliente.get(4).setValor(tfDireccion.getText());
            postCliente.get(5).setValor(tfCumpleanos.getText());
            postCliente.get(6).setValor(cbRelevancia.getSelectedIndex());
            postCliente.get(7).setValor(tfCorreo.getText());

            if (requests.post("http://localhost:8000/api/clientes/", postCliente)
                .equals("{\"Error\":\"Código ya existe\"}"))
            {
                JOptionPane.showMessageDialog(null, "El código ingresado ya existe");
            }
            else if (requests.post("http://localhost:8000/api/clientes/", postCliente)
                .equals("{\"cumpleanios\":[\"Date has wrong format. Use one of these formats instead: YYYY-MM-DD.\"]}"))
            {
                JOptionPane.showMessageDialog(null, "El cumpleaños debe de ir en este formato: Año-Mes-Día (AAAA-MM-DD)");
            }
            else
            {
                tfCodigo.setText("");
                tfNombre.setText("");
                tfTelefono.setText("");
                tfCumpleanos.setText("");
                cbRelevancia.setSelectedIndex(0);
                tfCorreo.setText("");
                tfNit.setText("");
                tfCumpleanos.setText("");
                tfDireccion.setText("");
                while (clientes.getRowCount() > 0)
                clientes.removeRow(0);
                cargarInformacion();
                JOptionPane.showMessageDialog(null, "Cliente ingresado satisfactoriamente");
            }
        }
        else
        JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JComboBox<String> cbModRelevancia;
    private javax.swing.JComboBox<String> cbRelevancia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblCumpleanos;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblInsercion;
    private javax.swing.JLabel lblModCorreo;
    private javax.swing.JLabel lblModCumpleanos;
    private javax.swing.JLabel lblModDireccion;
    private javax.swing.JLabel lblModNit;
    private javax.swing.JLabel lblModNombre;
    private javax.swing.JLabel lblModRelevancia;
    private javax.swing.JLabel lblModTelefono;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRelevancia;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel pnlGeneral;
    private javax.swing.JSeparator sepCodigo;
    private javax.swing.JSeparator sepColor;
    private javax.swing.JSeparator sepColor1;
    private javax.swing.JSeparator sepColor2;
    private javax.swing.JSeparator sepColor3;
    private javax.swing.JSeparator sepMarca;
    private javax.swing.JSeparator sepMarca1;
    private javax.swing.JSeparator sepModelo;
    private javax.swing.JSeparator sepModelo1;
    private javax.swing.JSeparator sepNombre;
    private javax.swing.JSeparator sepNombre1;
    private javax.swing.JSeparator sepNombre2;
    private javax.swing.JSeparator sepNombre3;
    private javax.swing.JTable tClientes;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfCumpleanos;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfModCorreo;
    private javax.swing.JTextField tfModCumpleanos;
    private javax.swing.JTextField tfModDireccion;
    private javax.swing.JTextField tfModNit;
    private javax.swing.JTextField tfModNombre;
    private javax.swing.JTextField tfModTelefono;
    private javax.swing.JTextField tfNit;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
