/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author User
 */
public class FRRHH extends javax.swing.JPanel {

    /**
     * Creates new form FRRHH
     */
    public FRRHH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeneral = new javax.swing.JPanel();
        lblRol = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        lblCContrasena = new javax.swing.JLabel();
        sepCodigo = new javax.swing.JSeparator();
        sepCContrasena = new javax.swing.JSeparator();
        tfNombre = new javax.swing.JTextField();
        sepNombre = new javax.swing.JSeparator();
        tfUsuario = new javax.swing.JTextField();
        sepUsuario = new javax.swing.JSeparator();
        tfContrasena = new javax.swing.JTextField();
        sepContrasena = new javax.swing.JSeparator();
        tfCContrasena = new javax.swing.JTextField();
        tfCodigo = new javax.swing.JTextField();
        lblFotografia = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnElegirImg = new javax.swing.JButton();
        lblElegirFtg = new javax.swing.JLabel();
        rbEmpleado = new javax.swing.JRadioButton();
        rbAdministrador = new javax.swing.JRadioButton();
        rbSAdministrador = new javax.swing.JRadioButton();
        lblCodigo = new javax.swing.JLabel();

        pnlGeneral.setBackground(new java.awt.Color(34, 51, 59));
        pnlGeneral.setPreferredSize(new java.awt.Dimension(1280, 680));
        pnlGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRol.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblRol.setForeground(new java.awt.Color(255, 255, 255));
        lblRol.setText("Rol");
        pnlGeneral.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, -1));

        lblNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");
        pnlGeneral.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario");
        pnlGeneral.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        lblContrasena.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Contraseña");
        pnlGeneral.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        lblCContrasena.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblCContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblCContrasena.setText("Confirmar contraseña");
        pnlGeneral.add(lblCContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 170, -1));
        pnlGeneral.add(sepCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 200, 0));
        pnlGeneral.add(sepCContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 200, -1));

        tfNombre.setBackground(new java.awt.Color(34, 51, 59));
        tfNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(255, 255, 255));
        tfNombre.setBorder(null);
        pnlGeneral.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 200, -1));
        pnlGeneral.add(sepNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 200, -1));

        tfUsuario.setBackground(new java.awt.Color(34, 51, 59));
        tfUsuario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfUsuario.setForeground(new java.awt.Color(255, 255, 255));
        tfUsuario.setBorder(null);
        pnlGeneral.add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 200, -1));
        pnlGeneral.add(sepUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 200, 10));

        tfContrasena.setBackground(new java.awt.Color(34, 51, 59));
        tfContrasena.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfContrasena.setForeground(new java.awt.Color(255, 255, 255));
        tfContrasena.setBorder(null);
        pnlGeneral.add(tfContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 200, -1));
        pnlGeneral.add(sepContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 200, -1));

        tfCContrasena.setBackground(new java.awt.Color(34, 51, 59));
        tfCContrasena.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfCContrasena.setForeground(new java.awt.Color(255, 255, 255));
        tfCContrasena.setBorder(null);
        pnlGeneral.add(tfCContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 200, -1));

        tfCodigo.setBackground(new java.awt.Color(34, 51, 59));
        tfCodigo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfCodigo.setForeground(new java.awt.Color(255, 255, 255));
        tfCodigo.setBorder(null);
        pnlGeneral.add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 200, -1));

        lblFotografia.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblFotografia.setForeground(new java.awt.Color(255, 255, 255));
        lblFotografia.setText("Fotografía");
        pnlGeneral.add(lblFotografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 80, -1, -1));

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ingresar.png"))); // NOI18N
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        pnlGeneral.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 310, 80));

        btnElegirImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Elegir imagen.png"))); // NOI18N
        pnlGeneral.add(btnElegirImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 290, 140, 30));

        lblElegirFtg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo imagen.png"))); // NOI18N
        pnlGeneral.add(lblElegirFtg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 210, 160));

        rbEmpleado.setBackground(new java.awt.Color(34, 51, 59));
        rbEmpleado.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        rbEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        rbEmpleado.setText("Empleado");
        rbEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEmpleadoActionPerformed(evt);
            }
        });
        pnlGeneral.add(rbEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        rbAdministrador.setBackground(new java.awt.Color(34, 51, 59));
        rbAdministrador.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        rbAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        rbAdministrador.setText("Administrador");
        rbAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAdministradorActionPerformed(evt);
            }
        });
        pnlGeneral.add(rbAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        rbSAdministrador.setBackground(new java.awt.Color(34, 51, 59));
        rbSAdministrador.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        rbSAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        rbSAdministrador.setText("SubAdministrador");
        rbSAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSAdministradorActionPerformed(evt);
            }
        });
        pnlGeneral.add(rbSAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("Código");
        pnlGeneral.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void rbEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEmpleadoActionPerformed

    private void rbAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAdministradorActionPerformed

    private void rbSAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSAdministradorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElegirImg;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblCContrasena;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblElegirFtg;
    private javax.swing.JLabel lblFotografia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlGeneral;
    private javax.swing.JRadioButton rbAdministrador;
    private javax.swing.JRadioButton rbEmpleado;
    private javax.swing.JRadioButton rbSAdministrador;
    private javax.swing.JSeparator sepCContrasena;
    private javax.swing.JSeparator sepCodigo;
    private javax.swing.JSeparator sepContrasena;
    private javax.swing.JSeparator sepNombre;
    private javax.swing.JSeparator sepUsuario;
    private javax.swing.JTextField tfCContrasena;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfContrasena;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
