/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author User
 */
public class FVenta extends javax.swing.JPanel {

    /**
     * Creates new form FVenta
     */
    public FVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeneral = new javax.swing.JPanel();
        lblQTotal = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblVendedor = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        sepNit = new javax.swing.JSeparator();
        sepContrasena = new javax.swing.JSeparator();
        tfDireccion = new javax.swing.JTextField();
        sepDireccion = new javax.swing.JSeparator();
        tfNit = new javax.swing.JTextField();
        sepVendedor = new javax.swing.JSeparator();
        tfContrasena = new javax.swing.JTextField();
        tfCliente = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        sepFacturacion = new javax.swing.JSeparator();
        sepCuenta = new javax.swing.JSeparator();
        sepCliente = new javax.swing.JSeparator();
        tfVendedor = new javax.swing.JTextField();
        lblNit = new javax.swing.JLabel();
        tfCodProducto = new javax.swing.JTextField();
        lblFacturacion = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();
        spFacturacion = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sepFiltro = new javax.swing.JSeparator();
        lblCantidad = new javax.swing.JLabel();
        spFiltro = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnDescuento = new javax.swing.JButton();
        btnFacturar = new javax.swing.JButton();
        lblCProducto = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        pnlGeneral.setBackground(new java.awt.Color(34, 51, 59));
        pnlGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQTotal.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblQTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblQTotal.setText("Q. 999999.99");
        pnlGeneral.add(lblQTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 620, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("Dirección");
        pnlGeneral.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        lblVendedor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblVendedor.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor.setText("Vendedor");
        pnlGeneral.add(lblVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, -1, -1));

        lblContrasena.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Contraseña");
        pnlGeneral.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 70, 100, -1));
        pnlGeneral.add(sepNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 260, 0));
        pnlGeneral.add(sepContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 90, 200, -1));

        tfDireccion.setBackground(new java.awt.Color(34, 51, 59));
        tfDireccion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfDireccion.setForeground(new java.awt.Color(255, 255, 255));
        tfDireccion.setBorder(null);
        pnlGeneral.add(tfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 270, 20));
        pnlGeneral.add(sepDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 270, -1));

        tfNit.setBackground(new java.awt.Color(34, 51, 59));
        tfNit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfNit.setForeground(new java.awt.Color(255, 255, 255));
        tfNit.setBorder(null);
        tfNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNitActionPerformed(evt);
            }
        });
        pnlGeneral.add(tfNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 260, -1));
        pnlGeneral.add(sepVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 200, -1));

        tfContrasena.setBackground(new java.awt.Color(34, 51, 59));
        tfContrasena.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfContrasena.setForeground(new java.awt.Color(255, 255, 255));
        tfContrasena.setBorder(null);
        pnlGeneral.add(tfContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 70, 200, -1));

        tfCliente.setBackground(new java.awt.Color(34, 51, 59));
        tfCliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfCliente.setForeground(new java.awt.Color(255, 255, 255));
        tfCliente.setBorder(null);
        pnlGeneral.add(tfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 260, -1));

        lblCliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCliente.setText("Cliente");
        pnlGeneral.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        pnlGeneral.add(sepFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 360, 1350, 10));

        sepCuenta.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlGeneral.add(sepCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 10, 110));
        pnlGeneral.add(sepCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 260, -1));

        tfVendedor.setBackground(new java.awt.Color(34, 51, 59));
        tfVendedor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tfVendedor.setForeground(new java.awt.Color(255, 255, 255));
        tfVendedor.setBorder(null);
        pnlGeneral.add(tfVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, 200, -1));

        lblNit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblNit.setForeground(new java.awt.Color(255, 255, 255));
        lblNit.setText("Nit");
        pnlGeneral.add(lblNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        tfCodProducto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pnlGeneral.add(tfCodProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 200, -1));

        lblFacturacion.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblFacturacion.setForeground(new java.awt.Color(255, 255, 255));
        lblFacturacion.setText("Facturación");
        pnlGeneral.add(lblFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        tfCantidad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pnlGeneral.add(tfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 130, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spFacturacion.setViewportView(jTable1);

        pnlGeneral.add(spFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 1230, 180));
        pnlGeneral.add(sepFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 110, 1350, -1));

        lblCantidad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("Cantidad");
        pnlGeneral.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spFiltro.setViewportView(jTable2);

        pnlGeneral.add(spFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1230, 150));

        btnDescuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Descuento.png"))); // NOI18N
        btnDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescuentoActionPerformed(evt);
            }
        });
        pnlGeneral.add(btnDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 120, 30));

        btnFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Facturar.png"))); // NOI18N
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });
        pnlGeneral.add(btnFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 120, 30));

        lblCProducto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblCProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblCProducto.setText("Código Producto");
        pnlGeneral.add(lblCProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        lblTotal.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total");
        pnlGeneral.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 620, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNitActionPerformed

    private void btnDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescuentoActionPerformed

    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescuento;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCProducto;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFacturacion;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblQTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JPanel pnlGeneral;
    private javax.swing.JSeparator sepCliente;
    private javax.swing.JSeparator sepContrasena;
    private javax.swing.JSeparator sepCuenta;
    private javax.swing.JSeparator sepDireccion;
    private javax.swing.JSeparator sepFacturacion;
    private javax.swing.JSeparator sepFiltro;
    private javax.swing.JSeparator sepNit;
    private javax.swing.JSeparator sepVendedor;
    private javax.swing.JScrollPane spFacturacion;
    private javax.swing.JScrollPane spFiltro;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfCliente;
    private javax.swing.JTextField tfCodProducto;
    private javax.swing.JTextField tfContrasena;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNit;
    private javax.swing.JTextField tfVendedor;
    // End of variables declaration//GEN-END:variables
}
