# Generated by Django 2.2.5 on 2020-03-20 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
        ('clienteServicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=80)),
                ('imei', models.CharField(max_length=17)),
                ('bateria', models.BooleanField(default=False)),
                ('cargador', models.BooleanField(default=False)),
                ('sim', models.BooleanField(default=False)),
                ('micro', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField()),
                ('accesorio', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=8)),
                ('clienteSerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clienteServicios.ClienteServicio')),
                ('marcaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marca.Marca')),
            ],
        ),
    ]
