# Generated by Django 2.2.5 on 2019-09-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=35)),
                ('modelo', models.CharField(max_length=45)),
                ('marca', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
                ('existencia', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=4, max_digits=8)),
                ('eliminado', models.BooleanField(default=False)),
                ('categoriaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
        ),
    ]
