# Generated by Django 3.0.4 on 2020-04-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('color', '0001_initial'),
        ('categoria', '0001_initial'),
        ('marca', '0002_marca_eliminado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
                ('existencia', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precioMayorista', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precioCliente', models.DecimalField(decimal_places=4, max_digits=12)),
                ('eliminado', models.BooleanField(default=False)),
                ('categoriaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.Categoria')),
                ('colorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.Color')),
                ('marcaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marca.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default=None, upload_to='')),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='producto.Producto')),
            ],
        ),
    ]
