# Generated by Django 2.2.5 on 2020-03-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('rol', models.BooleanField()),
                ('imagen', models.ImageField(default=None, upload_to='')),
                ('eliminado', models.BooleanField(default=False)),
                ('usuario', models.CharField(max_length=45)),
                ('contrasenia', models.CharField(max_length=30)),
            ],
        ),
    ]
