# Generated by Django 2.2.5 on 2020-04-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rh',
            name='contrasenia',
            field=models.CharField(max_length=40),
        ),
    ]
