/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vfix.reparaciones;

/**
 *
 * @author carlo
 */
public class Reparaciones extends javax.swing.JPanel {

    /**
     * Creates new form Reparaciones
     */
    public Reparaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnNuebaReparacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(54, 159, 128));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1080, 10));

        btnNuebaReparacion.setBackground(new java.awt.Color(26, 46, 70));
        btnNuebaReparacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnNuebaReparacion.setForeground(new java.awt.Color(255, 255, 255));
        btnNuebaReparacion.setText("+ Nueva Reparacion");
        btnNuebaReparacion.setBorder(null);
        btnNuebaReparacion.setBorderPainted(false);
        btnNuebaReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuebaReparacionActionPerformed(evt);
            }
        });
        add(btnNuebaReparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 240, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(54, 159, 128));
        jLabel1.setText("Reparaciones");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 300, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setBorder(null);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 190, 30));

        jSeparator2.setBackground(new java.awt.Color(54, 159, 128));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 190, 10));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 690, 200));

        jButton2.setBackground(new java.awt.Color(26, 46, 70));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Detalle");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuebaReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuebaReparacionActionPerformed
        // TODO add your handling code here:
        NuevaReparacion nuevaReparacion = new NuevaReparacion();
        nuevaReparacion.setVisible(true);
    }//GEN-LAST:event_btnNuebaReparacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuebaReparacion;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
