# Generated by Django 2.2.5 on 2019-10-02 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=4, max_digits=15)),
                ('descuento', models.DecimalField(decimal_places=4, max_digits=15)),
                ('venta', models.BooleanField()),
                ('garantia', models.BooleanField()),
                ('efectivo', models.BooleanField()),
                ('tarjeta', models.BooleanField()),
                ('fecha', models.DateTimeField()),
                ('eliminado', models.BooleanField(default=False)),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
    ]
