# Generated by Django 2.2.5 on 2020-03-20 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=8)),
                ('facturaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Factura')),
            ],
        ),
    ]
