# Generated by Django 2.2.5 on 2019-11-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=4, max_digits=8)),
                ('facturaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Factura')),
            ],
        ),
    ]
