# Generated by Django 2.2.5 on 2020-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallefactura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='subtotal',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
