# Generated by Django 3.0.4 on 2020-03-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteServicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteservicio',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
