/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.vfix.clientes;

import com.mycompany.vfix.estilos.TextPrompt;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author igeni
 */
public class AgregarCliente extends javax.swing.JDialog {
    //Coordenadas para lograr mover el JDialog 
    private int x;
    private int y;
    
    private FachadaClientes requests = new FachadaClientes();//A partir de esta variable es posible hacer el post
    /** Creates new form NewJDialog */
    public AgregarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);//Centrar JDialog
        placeHolders();//Asignar estilos a los jText
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtFechaNacimiento = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtCorreo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnEnviar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        txtNit = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtDireccion = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(26, 46, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 180, -1));

        btnCerrar.setBackground(new java.awt.Color(26, 46, 70));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.setBorder(null);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 40, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 159, 128)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.setToolTipText("");
        txtNombre.setBorder(null);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 260, 30));

        jSeparator1.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 260, 10));

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelefono.setBorder(null);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 260, 30));

        jSeparator2.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 260, 10));

        txtFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFechaNacimiento.setBorder(null);
        txtFechaNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaNacimientoKeyTyped(evt);
            }
        });
        jPanel2.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 260, 30));

        jSeparator3.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 260, 10));

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCorreo.setBorder(null);
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 260, 30));

        jSeparator4.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 260, 10));

        btnEnviar.setBackground(new java.awt.Color(26, 46, 70));
        btnEnviar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Ingresar Cliente");
        btnEnviar.setBorder(null);
        btnEnviar.setBorderPainted(false);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 260, 50));

        jSeparator5.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 190, 10));

        txtNit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNit.setBorder(null);
        txtNit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNitKeyTyped(evt);
            }
        });
        jPanel2.add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 260, 30));

        jSeparator6.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 260, 10));

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDireccion.setBorder(null);
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 260, 30));

        jSeparator7.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 260, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Cerrar jDialog
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.setVisible(false);//Cerrar el form
    }//GEN-LAST:event_btnCerrarActionPerformed
    //Validar un máximo de 55 caracteres y que se ingresen letras y espacios para el nombre
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char validacion = evt.getKeyChar();

        if (txtNombre.getText().length() > 55 || (!Character.isLetter(validacion) && validacion != ' '))
        evt.consume();

    }//GEN-LAST:event_txtNombreKeyTyped
    //Validar un máximo de 16 caracteres y que se ingresen sólo números, + y - para el teléfono
    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char validacion = evt.getKeyChar();

        if (txtTelefono.getText().length() > 16 || (!Character.isDigit(validacion) && validacion != '+' && validacion != '-'))
        evt.consume();
    }//GEN-LAST:event_txtTelefonoKeyTyped
    //Validar un máximo de 11 caracteres y que se ingrese la fecha de nacimiento en el formato: AAAA-MM-DD
    private void txtFechaNacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaNacimientoKeyTyped
        char validacion = evt.getKeyChar();

        if (txtFechaNacimiento.getText().length() > 11 || (!Character.isDigit(validacion) && validacion != '-'))
        evt.consume();
    }//GEN-LAST:event_txtFechaNacimientoKeyTyped
    //Validar un máximo de 25 caracteres y que se ingresen sólo letras en minúscula, dígitos, @ y _
    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        char validacion = evt.getKeyChar();

        if (txtCorreo.getText().length() > 25 || ((!Character.isLowerCase(validacion) && !(Character.isDigit(validacion))) && validacion != '@' && validacion != '_')
            && validacion != '.')
        evt.consume();
    }//GEN-LAST:event_txtCorreoKeyTyped
    //Enviar el request post
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if (txtNombre.getText().length() > 0 && txtTelefono.getText().length() > 0)
        {
            if (correoBienIngresado() && cumpleaniosBienIngresado())//Validar si el correo o el cumpleaños están bien ingresados
            {
                List<String> parametros = new ArrayList<String>();
                asignarParametros(parametros);
                requests.post(parametros);
                limpiarCajasdeTexto();
                JOptionPane.showMessageDialog(null, "El nuevo cliente ha sido ingresado con éxito");
            }
            else
            {
                if (!correoBienIngresado())
                    JOptionPane.showMessageDialog(null, "El correo no está bien ingresado");
                else if (!cumpleaniosBienIngresado())
                    JOptionPane.showMessageDialog(null, "El cumpleaños no está bien ingresado");
                else if (!correoBienIngresado() && !cumpleaniosBienIngresado())
                    JOptionPane.showMessageDialog(null, "El correo y el cumpleaños no están bien ingresados");
            }
        }
        else
        JOptionPane.showMessageDialog(null, "Los campos nombre y teléfono no pueden estar vacíos");
    }//GEN-LAST:event_btnEnviarActionPerformed
    //Validar un máximo de 20 caracteres y que se ingresen dígitos y -
    private void txtNitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNitKeyTyped
        char validacion = evt.getKeyChar();

        if (txtNit.getText().length() > 20 || (!Character.isDigit(validacion) && validacion != '-'))
        evt.consume();
    }//GEN-LAST:event_txtNitKeyTyped
    //Validar un máximo de 30 caracteres y que se ingresen letras o dígitos, - y espacios en blanco
    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        char validacion = evt.getKeyChar();

        if (txtDireccion.getText().length() > 30 || (!Character.isLetterOrDigit(validacion) && validacion != '-' && validacion != ' '))
        evt.consume();
    }//GEN-LAST:event_txtDireccionKeyTyped
    //Al mantener presionado click izquierdo y mover el mouse, el jDialog también se mueve
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x-x, point.y-y);
    }//GEN-LAST:event_formMouseDragged
    //Al presionar click izquierdo, es posible mover el jDialog
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
          x= evt.getX();
          y = evt.getY();
    }//GEN-LAST:event_formMousePressed
    //Limpiar todas las cajas de texto
    private void limpiarCajasdeTexto()
    {
        txtNombre.setText("");
        txtTelefono.setText("");
        txtNit.setText("");
        txtDireccion.setText("");
        txtFechaNacimiento.setText("");
        txtCorreo.setText("");
    }
    //Asignar los valores ingresados en las cajas de texto al arreglo dinámico
    private void asignarParametros(List<String> parametros)
    {
        parametros.add(txtNombre.getText());
        parametros.add(txtTelefono.getText());
        parametros.add(txtNit.getText());
        parametros.add(txtDireccion.getText());
        parametros.add(txtFechaNacimiento.getText());
        parametros.add("1");
        parametros.add(txtCorreo.getText());
    }
    //Verificar si el correo termina en @gmail.com o en @hotmail.com
    private boolean correoBienIngresado()
    {
        int largoCorreo = txtCorreo.getText().length();
        if (largoCorreo > 0)
        {
            String gmail = txtCorreo.getText().substring(largoCorreo-10, largoCorreo);
            String hotmail = txtCorreo.getText().substring(largoCorreo-12, largoCorreo);
            if (gmail.equals("@gmail.com") || hotmail.equals("@hotmail.com") || largoCorreo == 0)
               return true;
            else
               return false;
        }
        else
            return true;
    }
    //Verificar si el formato del cumpleaños está bien ingresado (AAAA-MM-DD
    private boolean cumpleaniosBienIngresado()
    {
        int guiones = 0;
        String Cumpleanios = txtFechaNacimiento.getText();
        if (Cumpleanios.length() > 0)
        {
            for (int i = 0; i < Cumpleanios.length(); i++)
            {
                if (Cumpleanios.charAt(i) == '-')
                    guiones ++;
            }
            if ((guiones == 2) && (Cumpleanios.charAt(4) == '-' && Cumpleanios.charAt(7) == '-') || Cumpleanios.length() == 0)
                return true;
            else
                return false;
        }
        else
            return true;
    }
    //Insertar diseños a las cajas de texto
    public void placeHolders(){
        TextPrompt nombre = new TextPrompt("*Nombre", txtNombre);
        TextPrompt telefono = new TextPrompt("*Teléfono", txtTelefono);
        TextPrompt fecha = new TextPrompt("Fecha de Nacimiento (2019-01-01)", txtFechaNacimiento);
        TextPrompt correo = new TextPrompt("Correo (ejemplo@gmail.com)", txtCorreo);
        TextPrompt nit = new TextPrompt("Nit", txtNit);
        TextPrompt direccion = new TextPrompt("Dirección", txtDireccion);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarCliente dialog = new AgregarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

}
