/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vfix.clientes;

import com.mycompany.vfix.estilos.TextPrompt;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author igeni
 */
public class ModificarCliente extends javax.swing.JDialog {

    //Coordenadas para lograr mover el JDialog 
    private int x;
    private int y;
    
    static Integer id;//Id del cliente recepcionado
    static Cliente cliente;//Objeto correspondiente al cliente recepcionado
    FachadaClientes requests = new FachadaClientes();//Variable para realizar los requests
    /**
     * Creates new form ModificarCliente1
     */
    public ModificarCliente(java.awt.Frame parent, boolean modal, Integer id, Cliente cliente) {
        super(parent, modal);
        initComponents();
        this.id = id;//Obtener id del cliente
        this.cliente = cliente;//Obtener objeto (atributos) del cliente
        this.setLocationRelativeTo(null);
        estrellasIniciales(cliente);//Marcar las estrellas que ya tiene el cliente
        inicializarCampos();
        placeHolders();//Asignar estilos a los jText
    }

    //Inicializar el texto de los JTextField con los campos del cliente
    public void inicializarCampos()
    {
        txtNombre.setText(cliente.getNombre());
        txtTelefono.setText(cliente.getTelefono());
        txtFechaNacimiento.setText(cliente.getCumpleanios());
        txtCorreo.setText(cliente.getCorreo());
        txtNit.setText(cliente.getNit());
        txtDireccion.setText(cliente.getDireccion());
    }
    //Iniciar el uso de estrellas con las que tiene en el momento de iniciar el JDialog el cliente
    public void estrellasIniciales(Cliente cliente)
    {
        if (cliente.getEstrellas() == 1)
            usarRadioButtons(true, false, false, false, false);
        else if (cliente.getEstrellas() == 2)
            usarRadioButtons(true, true, false, false, false);
        else if (cliente.getEstrellas() == 3)
            usarRadioButtons(true, true, true, false, false);
        else if (cliente.getEstrellas() == 4)
            usarRadioButtons(true, true, true, true, false);
        else if (cliente.getEstrellas() == 5)
            usarRadioButtons(true, true, true, true, true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtFechaNacimiento = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtCorreo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnEnviar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        lblCinco = new javax.swing.JLabel();
        lblUna = new javax.swing.JLabel();
        lblDos = new javax.swing.JLabel();
        lblTres = new javax.swing.JLabel();
        lblCuatro = new javax.swing.JLabel();
        rbCinco = new javax.swing.JRadioButton();
        rbUna = new javax.swing.JRadioButton();
        rbDos = new javax.swing.JRadioButton();
        rbTres = new javax.swing.JRadioButton();
        rbCuatro = new javax.swing.JRadioButton();
        txtNit = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtDireccion = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(26, 46, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificar datos de: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 370, -1));

        btnCerrar.setBackground(new java.awt.Color(26, 46, 70));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.setBorder(null);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 40, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 159, 128)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.setToolTipText("");
        txtNombre.setBorder(null);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 260, 30));

        jSeparator1.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 260, 10));

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelefono.setBorder(null);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 260, 30));

        jSeparator2.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 260, 10));

        txtFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFechaNacimiento.setBorder(null);
        txtFechaNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaNacimientoKeyTyped(evt);
            }
        });
        jPanel2.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 260, 30));

        jSeparator3.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 260, 10));

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCorreo.setBorder(null);
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 260, 30));

        jSeparator4.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 260, 10));

        btnEnviar.setBackground(new java.awt.Color(26, 46, 70));
        btnEnviar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Modificar datos");
        btnEnviar.setBorder(null);
        btnEnviar.setBorderPainted(false);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 260, 50));

        jSeparator5.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 190, 10));

        lblCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Estrella - copia.png"))); // NOI18N
        jPanel2.add(lblCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 60, 60));

        lblUna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Estrella - copia.png"))); // NOI18N
        jPanel2.add(lblUna, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 60, 60));

        lblDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Estrella - copia.png"))); // NOI18N
        jPanel2.add(lblDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 60, 60));

        lblTres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Estrella - copia.png"))); // NOI18N
        jPanel2.add(lblTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 60, 60));

        lblCuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Estrella - copia.png"))); // NOI18N
        jPanel2.add(lblCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 60, 60));

        rbCinco.setBackground(new java.awt.Color(255, 255, 255));
        rbCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCincoActionPerformed(evt);
            }
        });
        jPanel2.add(rbCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 30, -1));

        rbUna.setBackground(new java.awt.Color(255, 255, 255));
        rbUna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUnaActionPerformed(evt);
            }
        });
        jPanel2.add(rbUna, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, -1));

        rbDos.setBackground(new java.awt.Color(255, 255, 255));
        rbDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDosActionPerformed(evt);
            }
        });
        jPanel2.add(rbDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, -1));

        rbTres.setBackground(new java.awt.Color(255, 255, 255));
        rbTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTresActionPerformed(evt);
            }
        });
        jPanel2.add(rbTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 30, -1));

        rbCuatro.setBackground(new java.awt.Color(255, 255, 255));
        rbCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCuatroActionPerformed(evt);
            }
        });
        jPanel2.add(rbCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 30, -1));

        txtNit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNit.setBorder(null);
        txtNit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNitKeyTyped(evt);
            }
        });
        jPanel2.add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 260, 30));

        jSeparator6.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 260, 10));

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDireccion.setBorder(null);
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 260, 30));

        jSeparator7.setBackground(new java.awt.Color(54, 159, 128));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 260, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(1, 1, 1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Cerrar el JDialog
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.setVisible(false);//Cerrar el form
    }//GEN-LAST:event_btnCerrarActionPerformed
    //Validar que el nombre tenga sólo letras y espacios, y validar que tenga una longitud menor o igual a 55 caracteres
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char validacion = evt.getKeyChar();

        if (txtNombre.getText().length() > 55 || (!Character.isLetter(validacion) && validacion != ' '))
        evt.consume();
    }//GEN-LAST:event_txtNombreKeyTyped
    //Validar que el teléfono sólo tenga + y números, y que tenga una longitud menor o igual a 16 caracteres
    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char validacion = evt.getKeyChar();

        if (txtTelefono.getText().length() > 16 || (!Character.isDigit(validacion) && validacion != '+' && validacion != '-'))
        evt.consume();
    }//GEN-LAST:event_txtTelefonoKeyTyped
    //Validar que la fecha de nacimiento tenga - y números, y que no sea mayor a 11 caracteres
    private void txtFechaNacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaNacimientoKeyTyped
        char validacion = evt.getKeyChar();

        if (txtFechaNacimiento.getText().length() > 11 || (!Character.isDigit(validacion) && validacion != '-'))
        evt.consume();
    }//GEN-LAST:event_txtFechaNacimientoKeyTyped
    //Validar que el correo tenga @, _, letras y dígitos, y que no sea mayor a 25 caracteres
    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        char validacion = evt.getKeyChar();

        if (txtCorreo.getText().length() > 25 || ((!Character.isLowerCase(validacion) && !(Character.isDigit(validacion))) && validacion != '@' && validacion != '_')
            && validacion != '.')
        evt.consume();
    }//GEN-LAST:event_txtCorreoKeyTyped
    //Modificar al cliente
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        //Si los campos nombre y teléfono están rellenados
        if (txtNombre.getText().length() > 0 && txtTelefono.getText().length() > 0)
        {//Si el correo, el cumpleaños y el nit están bien ingresados
            if (correoBienIngresado() && cumpleaniosBienIngresado() && (nitBienIngresado() || txtNit.getText().equals("c/f")))//Validar si el correo o el cumpleaños están bien ingresados
            {
                //Realizar request post
                List<String> parametros = new ArrayList<String>();
                asignarParametros(parametros);
                Integer id = this.id;
                requests.put(parametros, id);
                JOptionPane.showMessageDialog(null, "El cliente ha sido modificado con éxito");
                this.setVisible(false);//Cerrar el form
            }
            else//Si no, indicar qué no se ha ingresado bien
            {
                if (!correoBienIngresado())
                JOptionPane.showMessageDialog(null, "El correo no está bien ingresado");
                else if (!cumpleaniosBienIngresado())
                JOptionPane.showMessageDialog(null, "El cumpleaños no está bien ingresado");
                else if (!nitBienIngresado())
                JOptionPane.showMessageDialog(null, "El nit no está bien ingresado");
                else if (!correoBienIngresado() && !cumpleaniosBienIngresado())
                JOptionPane.showMessageDialog(null, "El correo y el cumpleaños no están bien ingresados");
                else if (!correoBienIngresado() && !nitBienIngresado())
                JOptionPane.showMessageDialog(null, "El correo y el nit no están bien ingresados");
                else if (!cumpleaniosBienIngresado() && nitBienIngresado())
                JOptionPane.showMessageDialog(null, "El cumpleaños y el nit no están bien ingresados");
                else if (!cumpleaniosBienIngresado() && !nitBienIngresado() && !correoBienIngresado())
                JOptionPane.showMessageDialog(null, "El correo, el nit y el cumpleaños no están bien ingresados");
            }
        }
        else
        JOptionPane.showMessageDialog(null, "Los campos nombre y teléfono no pueden estar vacíos");
    }//GEN-LAST:event_btnEnviarActionPerformed
    //Activar la quinta estrella
    private void rbCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCincoActionPerformed
        if (!rbCinco.isSelected())
        rbCinco.setSelected(true);
        if (rbCinco.isSelected())
        usarRadioButtons(true, true, true, true, true);
    }//GEN-LAST:event_rbCincoActionPerformed
    //Activar la primer estrella
    private void rbUnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUnaActionPerformed
        if (!rbUna.isSelected())
        rbUna.setSelected(true);
        if (rbUna.isSelected())
        usarRadioButtons(true, false, false, false, false);
    }//GEN-LAST:event_rbUnaActionPerformed
    //Activar la tercer estrella
    private void rbDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDosActionPerformed
        if (!rbDos.isSelected())
        rbDos.setSelected(true);
        if (rbDos.isSelected())
        usarRadioButtons(true, true, false, false, false);
    }//GEN-LAST:event_rbDosActionPerformed
    //Activar la segunda estrella
    private void rbTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTresActionPerformed
        if (!rbTres.isSelected())
        rbTres.setSelected(true);
        if (rbTres.isSelected())
        usarRadioButtons(true, true, true, false, false);
    }//GEN-LAST:event_rbTresActionPerformed
    //Activar la cuarta estrella
    private void rbCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCuatroActionPerformed
        if (!rbCuatro.isSelected())
        rbCuatro.setSelected(true);
        if (rbCuatro.isSelected())
        usarRadioButtons(true, true, true, true, false);
    }//GEN-LAST:event_rbCuatroActionPerformed
    //Verificar que el nit contenga sólo números y guiones, y que no sea mayor a 20 caracteres
    private void txtNitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNitKeyTyped
        char validacion = evt.getKeyChar();

        if (txtNit.getText().length() > 20 || (!Character.isDigit(validacion) && validacion != '-'))
        evt.consume();
    }//GEN-LAST:event_txtNitKeyTyped
    //Verificar que la dirección contenga sólo letras, números, - y espacios en blanco, y que no sea mayor a 30 caracteres
    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        char validacion = evt.getKeyChar();

        if (txtDireccion.getText().length() > 30 || (!Character.isLetterOrDigit(validacion) && validacion != '-' && validacion != ' '))
        evt.consume();
    }//GEN-LAST:event_txtDireccionKeyTyped
    //Al presionar el click izquierdo, se habilita el desplazamiento del JDialog a cualquier parte de la pantalla
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x= evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed
    //Al mantener presionado el click izquierdo, se puede mover de un lado a otro el JDialog en la pantalla
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x-x, point.y-y);
    }//GEN-LAST:event_formMouseDragged

     //Activar o desactivar los radiobutton
    private void usarRadioButtons(boolean uno, boolean dos, boolean tres, boolean cuatro, boolean cinco)
    {
        rbUna.setSelected(uno);
        rbDos.setSelected(dos);
        rbTres.setSelected(tres);
        rbCuatro.setSelected(cuatro);
        rbCinco.setSelected(cinco);
        lblUna.setEnabled(uno);
        lblDos.setEnabled(dos);
        lblTres.setEnabled(tres);
        lblCuatro.setEnabled(cuatro);
        lblCinco.setEnabled(cinco);
    }
    
    //Asignar los valores ingresados en las cajas de texto al arreglo dinámico
    private void asignarParametros(List<String> parametros)
    {
        parametros.add(txtNombre.getText());
        parametros.add(txtTelefono.getText());
        if (txtNit.getText().equals(""))
            parametros.add("c/f");
        else
            parametros.add(txtNit.getText());
        if (txtDireccion.getText().equals(""))
            parametros.add("ciudad");
        else
            parametros.add(txtDireccion.getText());
        parametros.add(txtFechaNacimiento.getText());
        if (rbCinco.isSelected())
            parametros.add("5");
        else if (rbCuatro.isSelected())
            parametros.add("4");
        else if (rbTres.isSelected())
            parametros.add("3");
        else if (rbDos.isSelected())
            parametros.add("2");
        else if (rbUna.isSelected())
            parametros.add("1");
        parametros.add(txtCorreo.getText());
    }
    
    //Verificar si el correo termina en @gmail.com o en @hotmail.com
    private boolean correoBienIngresado()
    {
        int largoCorreo = txtCorreo.getText().length();
        if (largoCorreo > 0)
        {
            String gmail = txtCorreo.getText().substring(largoCorreo-10, largoCorreo);
            String hotmail = txtCorreo.getText().substring(largoCorreo-12, largoCorreo);
            if (gmail.equals("@gmail.com") || hotmail.equals("@hotmail.com") || largoCorreo == 0)
               return true;
            else
               return false;
        }
        else
            return true;
    }
    //Verificar si el formato del cumpleaños está bien ingresado (AAAA-MM-DD
    private boolean cumpleaniosBienIngresado()
    {
        int guiones = 0;
        String Cumpleanios = txtFechaNacimiento.getText();
        if (Cumpleanios.length() > 0)
        {
            for (int i = 0; i < Cumpleanios.length(); i++)
            {
                if (Cumpleanios.charAt(i) == '-')
                    guiones ++;
            }
            if ((guiones == 2) && (Cumpleanios.charAt(4) == '-' && Cumpleanios.charAt(7) == '-') || Cumpleanios.length() == 0)
                return true;
            else
                return false;
        }
        else
            return true;
    }
    
    //Validar que el nit no sea "c" o "c/ o cualquier posible combinación con "c/f"
    private boolean nitBienIngresado()
    {
        for (int i = 0; i < txtNit.getText().length(); i++)
        {
            if (Character.isLetter(txtNit.getText().charAt(i)) && txtNit.getText().charAt(i) != '-')
                return false;
        }
        return true;
    }
    //Habilitar modelos para las acjas de texto
    public void placeHolders(){
        TextPrompt nombre = new TextPrompt("*Nombre", txtNombre);
        TextPrompt telefono = new TextPrompt("*Teléfono", txtTelefono);
        TextPrompt fecha = new TextPrompt("Fecha de Nacimiento (2019-01-01)", txtFechaNacimiento);
        TextPrompt correo = new TextPrompt("Correo (ejemplo@gmail.com)", txtCorreo);
        TextPrompt nit = new TextPrompt("Nit", txtNit);
        TextPrompt direccion = new TextPrompt("Dirección", txtDireccion);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarCliente dialog = new ModificarCliente(new javax.swing.JFrame(), true, id, cliente);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblCinco;
    private javax.swing.JLabel lblCuatro;
    private javax.swing.JLabel lblDos;
    private javax.swing.JLabel lblTres;
    private javax.swing.JLabel lblUna;
    private javax.swing.JRadioButton rbCinco;
    private javax.swing.JRadioButton rbCuatro;
    private javax.swing.JRadioButton rbDos;
    private javax.swing.JRadioButton rbTres;
    private javax.swing.JRadioButton rbUna;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
